<?php
/**
 * Where generated CSVs live on disk, and how they're kept private.
 *
 * A fulfillment report is customer PII (names, emails, optionally postal
 * addresses), so the file must not be guessable or directly fetchable.
 * Three layers, deliberately, because no single one is sufficient:
 *
 *   1. An unguessable filename — 32 hex characters from wp_generate_password()
 *      via random_bytes(). This is the layer that actually holds on every
 *      server, and it's why it isn't merely decorative.
 *   2. `.htaccess` denying direct access. Real protection on Apache,
 *      completely inert on nginx — which is exactly why it isn't relied on
 *      alone. SiteHealth surfaces this so the operator knows.
 *   3. Downloads are only ever served through AdminPage's admin-post handler,
 *      which checks capability and nonce before streaming the bytes.
 *
 * @package BLT\SCE
 */

namespace BLT\SCE\Modules\Reports;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class ReportStorage
 */
final class ReportStorage {

	const DIRECTORY = 'blt-sce-reports';

	/**
	 * Resolved directory path, memoized for the request. The reports list
	 * checks every row's file, and re-running the mkdir/guard stat calls per
	 * row is pure waste.
	 *
	 * @var string|null
	 */
	private $resolved;

	/**
	 * Absolute path to the report directory, creating and protecting it on
	 * first use.
	 *
	 * @return string|\WP_Error
	 */
	public function directory() {
		if ( null !== $this->resolved ) {
			return $this->resolved;
		}

		$uploads = wp_upload_dir();

		if ( ! empty( $uploads['error'] ) ) {
			return new \WP_Error( 'blt_sce_uploads_unavailable', (string) $uploads['error'] );
		}

		$dir = trailingslashit( $uploads['basedir'] ) . self::DIRECTORY;

		if ( ! wp_mkdir_p( $dir ) ) {
			return new \WP_Error(
				'blt_sce_report_dir_failed',
				sprintf(
					/* translators: %s: directory path */
					__( 'Could not create the report directory at %s.', 'blt-surecart-extensions' ),
					$dir
				)
			);
		}

		$this->protect( $dir );

		$this->resolved = $dir;

		return $dir;
	}

	/**
	 * Drop the guard files in place if they're missing.
	 *
	 * @param string $dir Report directory.
	 * @return void
	 */
	private function protect( $dir ) {
		$htaccess = trailingslashit( $dir ) . '.htaccess';

		if ( ! file_exists( $htaccess ) ) {
			// Both syntaxes: Apache 2.4 uses Require, 2.2 uses Allow/Deny.
			$rules = "# Generated by BLT SureCart Extensions. Reports contain customer data.\n"
				. "<IfModule mod_authz_core.c>\n\tRequire all denied\n</IfModule>\n"
				. "<IfModule !mod_authz_core.c>\n\tOrder allow,deny\n\tDeny from all\n</IfModule>\n";

			file_put_contents( $htaccess, $rules ); // phpcs:ignore WordPress.WP.AlternativeFunctions
		}

		$index = trailingslashit( $dir ) . 'index.html';

		if ( ! file_exists( $index ) ) {
			file_put_contents( $index, '' ); // phpcs:ignore WordPress.WP.AlternativeFunctions
		}
	}

	/**
	 * Build a fresh, unguessable filename for a report.
	 *
	 * @param int    $report_id Report row ID.
	 * @param string $type      Report type slug.
	 * @return string Basename only, never a path.
	 */
	public function new_filename( $report_id, $type = 'fulfillment' ) {
		$token = wp_generate_password( 32, false, false );

		return sprintf(
			'%s-%d-%s-%s.csv',
			sanitize_key( $type ),
			(int) $report_id,
			gmdate( 'Ymd-His' ),
			strtolower( $token )
		);
	}

	/**
	 * Absolute path for a stored report file.
	 *
	 * The filename is passed through basename() and validated against a
	 * strict pattern so a crafted value can never escape the directory.
	 *
	 * @param string $filename Basename of the file.
	 * @return string|\WP_Error
	 */
	public function path( $filename ) {
		$filename = basename( (string) $filename );

		if ( ! preg_match( '/^[A-Za-z0-9._-]+\.csv$/', $filename ) ) {
			return new \WP_Error( 'blt_sce_bad_report_filename', __( 'Invalid report filename.', 'blt-surecart-extensions' ) );
		}

		$dir = $this->directory();

		if ( is_wp_error( $dir ) ) {
			return $dir;
		}

		return trailingslashit( $dir ) . $filename;
	}

	/**
	 * Whether a stored report file exists and is readable.
	 *
	 * @param string $filename Basename of the file.
	 * @return bool
	 */
	public function exists( $filename ) {
		$path = $this->path( $filename );

		return ! is_wp_error( $path ) && is_readable( $path );
	}

	/**
	 * Delete a stored report file. Missing files are not an error — the row
	 * may outlive the file if an operator cleared uploads by hand.
	 *
	 * @param string $filename Basename of the file.
	 * @return void
	 */
	public function delete( $filename ) {
		$path = $this->path( $filename );

		if ( is_wp_error( $path ) || ! file_exists( $path ) ) {
			return;
		}

		wp_delete_file( $path );
	}

	/**
	 * Whether the directory sits behind an `.htaccess` that a non-Apache
	 * server will ignore. Reported by Site Health so the operator can add an
	 * equivalent nginx rule if they want belt-and-braces protection.
	 *
	 * @return bool
	 */
	public function htaccess_present() {
		$uploads = wp_upload_dir();

		if ( ! empty( $uploads['error'] ) ) {
			return false;
		}

		return file_exists( trailingslashit( $uploads['basedir'] ) . self::DIRECTORY . '/.htaccess' );
	}
}
